apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  # this type of service is only good for development
  # other types of services include
  # ClusterIP, Ingress, LoadBalancer
  type: NodePort
  ports:
    - port: 3050 # port used within the k8s cluster by other pods to access this pod
      targetPort: 3000 # represent the port defined in the Pod declaration, it should be the port of the service that it listens on
      # used for directly accessing this pod from the browser or some other mechanism using the `host:${nodePort}` signature
      # its usually between 30000 - 32767
      # if it's not defined, then one will be randomly assigned to this pod
      nodePort: 31515
  selector:
    # this can be arbitrary but must match the label in the Pod file
    # you want to link it to
    component: web