version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:latest

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    stdin_open: true

    build:
      context: ./client
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3050:80"