version: "3"
services:
  client:
    image: "cooproton12/complex-client"
    mem_limit: 128m
    hostname: client

  server:
    image: "cooproton12/complex-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT

  worker:
    image: "cooproton12/complex-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "cooproton12/complex-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"