name: Sample Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
    - 'frontend/**'
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Navigate to frontend directory
        run: cd frontend

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

  test:
    needs: setup
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: check whats going on
        run: |
          ls
          echo "here's the ish"
          pwd

      - name: Run test for Frontend
        run: npm run test