name: Sample Docker Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
    - 'frontend/**'
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: commitSha
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build tagged docker image
        run: docker build -f Dockerfile.dev . -t cooproton12/frontend-stuff

      - name: Run test
        run: docker run -e CI=true cooproton12/frontend-stuff npm run test